# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterFace.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 500)
        Form.setMinimumSize(QtCore.QSize(600, 400))
        Form.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_Hero = QtWidgets.QPushButton(Form)
        self.pushButton_Hero.setObjectName("pushButton_Hero")
        self.verticalLayout.addWidget(self.pushButton_Hero)
        self.pushButton_Ability = QtWidgets.QPushButton(Form)
        self.pushButton_Ability.setObjectName("pushButton_Ability")
        self.verticalLayout.addWidget(self.pushButton_Ability)
        self.pushButton_Unit = QtWidgets.QPushButton(Form)
        self.pushButton_Unit.setObjectName("pushButton_Unit")
        self.verticalLayout.addWidget(self.pushButton_Unit)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton_Clean = QtWidgets.QPushButton(Form)
        self.pushButton_Clean.setObjectName("pushButton_Clean")
        self.verticalLayout.addWidget(self.pushButton_Clean)
        self.pushButton_Config = QtWidgets.QPushButton(Form)
        self.pushButton_Config.setObjectName("pushButton_Config")
        self.verticalLayout.addWidget(self.pushButton_Config)
        self.pushButton_Copy = QtWidgets.QPushButton(Form)
        self.pushButton_Copy.setObjectName("pushButton_Copy")
        self.verticalLayout.addWidget(self.pushButton_Copy)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.plainTextEdit_OldData = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_OldData.setObjectName("plainTextEdit_OldData")
        self.verticalLayout_2.addWidget(self.plainTextEdit_OldData)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.plainTextEdit_NewData = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_NewData.setObjectName("plainTextEdit_NewData")
        self.verticalLayout_2.addWidget(self.plainTextEdit_NewData)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        self.pushButton_Clean.clicked.connect(self.plainTextEdit_NewData.clear) # type: ignore
        self.pushButton_Clean.clicked.connect(self.plainTextEdit_OldData.clear) # type: ignore
        self.pushButton_Copy.clicked.connect(self.plainTextEdit_NewData.selectAll) # type: ignore
        self.pushButton_Copy.clicked.connect(self.plainTextEdit_NewData.copy) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "Top"))
        self.label.setText(_translate("Form", "Config"))
        self.pushButton_Hero.setText(_translate("Form", "Hero"))
        self.pushButton_Ability.setText(_translate("Form", "Ability"))
        self.pushButton_Unit.setText(_translate("Form", "Unit"))
        self.label_2.setText(_translate("Form", "Control"))
        self.pushButton_Clean.setText(_translate("Form", "Clean"))
        self.pushButton_Config.setText(_translate("Form", "Config"))
        self.pushButton_Copy.setText(_translate("Form", "Copy"))
        self.label_3.setText(_translate("Form", "OldData"))
        self.label_4.setText(_translate("Form", "NewData"))
